uses: actions/cache@v3
with:
    path: |
      # List paths to cache
      node_modules
      # Do not cache the _site folder
    key: ${{ runner.os }}-build-${{ hashFiles('**./storage') }}


exclude:
  - "games/eccothedolphin/Ecco the Dolphin (USA, Europe).md"
  - "games/gunstarheroes/Gunstar Heroes (USA).md"
  - "games/phantasystariv/Phantasy Star IV (USA).md"
  - "games/rangerx/Ranger X (Europe).md"
  - "games/ristar/Ristar (USA, Europe) (August 1994).md"
  - "games/shiningforce/Shining Force (USA).md"
  - "games/shinobiiii/Shinobi III - Return of the Ninja Master (USA).md"
  - "games/sonicthehedgehog/Sonic The Hedgehog (USA, Europe).md"
  - "games/sonicthehedgehog2/Sonic The Hedgehog 2 (World).md"
  - "games/streetsofrage2/Streets of Rage 2 (USA).md"
  - "games/vectorman/Vectorman (USA, Europe).md"
  - "games/vectorman2/Vectorman 2 (USA).md"
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main





