exclude:
  - "games/eccothedolphin/Ecco the Dolphin (USA, Europe).md"
  - "games/gunstarheroes/Gunstar Heroes (USA).md"
  - "games/phantasystariv/Phantasy Star IV (USA).md"
  - "games/rangerx/Ranger X (Europe).md"
  - "games/ristar/Ristar (USA, Europe) (August 1994).md"
  - "games/shiningforce/Shining Force (USA).md"
  - "games/shinobiiii/Shinobi III - Return of the Ninja Master (USA).md"
  - "games/sonicthehedgehog/Sonic The Hedgehog (USA, Europe).md"
  - "games/sonicthehedgehog2/Sonic The Hedgehog 2 (World).md"
  - "games/streetsofrage2/Streets of Rage 2 (USA).md"
  - "games/vectorman/Vectorman (USA, Europe).md"
  - "games/vectorman2/Vectorman 2 (USA).md"
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build project
        run: |
          # Add your build commands here
          echo "Building project..."

      - name: Deploy to GitHub Pages
        run: |
          # Your deployment commands here, like pushing to gh-pages
          echo "Deploying to GitHub Pages..."


