name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ... Other steps like building your project ...

      # Conditional artifact upload step
      - name: Upload Artifacts
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/main')
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: |
            # Here, specify the paths you want to upload,
            # Exclude non-code files or folders if necessary.
            # For example, upload only markdown files, js, css, etc.
            **/*.md
            **/*.js
            **/*.css
            !**storage/** # Exclude the entire storage folder
            !**apps/** # Exclude the entire storage folder
            !**games/** # Exclude the entire storage folder
            !**/*.bin # Exclude binary files
            !**/*.exe # Exclude executable files
            !**/*.zip # Exclude compressed files
            !**/*.tar # Exclude tar files
            !**/*.jpg # Exclude image files
            !**/*.png # Exclude image files
            !**/*.html # Test

exclude:
  - "games/eccothedolphin/Ecco the Dolphin (USA, Europe).md"
  - "games/gunstarheroes/Gunstar Heroes (USA).md"
  - "games/phantasystariv/Phantasy Star IV (USA).md"
  - "games/rangerx/Ranger X (Europe).md"
  - "games/ristar/Ristar (USA, Europe) (August 1994).md"
  - "games/shiningforce/Shining Force (USA).md"
  - "games/shinobiiii/Shinobi III - Return of the Ninja Master (USA).md"
  - "games/sonicthehedgehog/Sonic The Hedgehog (USA, Europe).md"
  - "games/sonicthehedgehog2/Sonic The Hedgehog 2 (World).md"
  - "games/streetsofrage2/Streets of Rage 2 (USA).md"
  - "games/vectorman/Vectorman (USA, Europe).md"
  - "games/vectorman2/Vectorman 2 (USA).md"
 

#Thereareproblemshere
#LOADRIGHTNOW
#YOUBETTERDOTHAT
#YOUMUSTDOIT
#WHYARENTYOU




