name: Create index.html Artifact

on:
  push:
    branches:
      - main  # or whichever branch you want to trigger the action

jobs:
  create-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Upload index.html as artifact
        uses: actions/upload-artifact@v3
        with:
          name: index-html
          path: index.html
