name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or whichever branch you want to trigger the action

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Upload index.html as artifact
        uses: actions/upload-artifact@v3
        with:
          name: index-html
          path: index.html
      
      # Add your build steps here if needed
      # For example:
      # - name: Build project
      #   run: npm run build
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # or your build directory if you have one
